services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:nightly@sha256:c06903e7e17b1e9ae9cf681841fed1fa5a40880420b61781cc8aea5c8fc5b2bd
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/aiostreams/data:/app/data
    networks:
      dmz:
        ipv4_address: 10.10.100.65
networks:
  dmz:
    external: true
