"""Render validated inventory into machine-owned Markdown views."""

from __future__ import annotations

import json
import math
import os
import re
import shutil
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Mapping
from zoneinfo import ZoneInfo

from skynet import cache


class RenderError(Exception):
    """A factual render could not be completed without partial publication."""

    def __init__(self, message: str, code: int = 1) -> None:
        super().__init__(message)
        self.code = code


@dataclass(frozen=True)
class RenderResult:
    output: Path
    pages: tuple[Path, ...]


def _json_optional(path: Path) -> Any | None:
    try:
        if not path.is_file() or path.stat().st_size == 0:
            return None
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        raise RenderError(f"{path}: malformed or unavailable inventory", 3) from None


def _object(value: Any, source: Path) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise RenderError(f"{source}: expected an object")
    return value


def _objects(value: Any, source: Path, field: str) -> list[dict[str, Any]]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise RenderError(f"{source}: {field} must be an array")
    if not all(isinstance(item, dict) for item in value):
        raise RenderError(f"{source}: {field} contains a malformed row")
    return value


def _text(value: Any, default: str = "") -> str:
    if value is None:
        return default
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _filename(value: str, source: Path) -> str:
    if value in {".", ".."} or re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", value) is None:
        raise RenderError(f"{source}: node name is not a safe page basename")
    return value


def _lines(*items: str) -> list[str]:
    return list(items)


def _frontmatter(title: str, timestamp: str, *tags: str) -> list[str]:
    suffix = "".join(f", {tag}" for tag in tags)
    return [
        "---",
        f"title: {title}",
        f"generated: {timestamp}",
        f"tags: [skynet, generated{suffix}]",
        "---",
        "",
    ]


def _footer(timestamp: str) -> list[str]:
    return [
        "",
        "> [!note] Auto-generated by `skynet render docs` — do not edit by hand. "
        f"Last run {timestamp}.",
        "",
    ]


def _read_query(repo: Path, name: str) -> str:
    path = repo / "scripts/sql" / name
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        raise RenderError(f"{path}: query source unavailable", 3) from None


def _cache_rows(repo: Path) -> tuple[list[tuple[str, ...]], list[tuple[str, ...]]]:
    try:
        result = cache.build(repo)
        hosts = cache.query(result.database, _read_query(repo, "host-map.sql")).rows
        vhosts = cache.query(result.database, _read_query(repo, "vhosts.sql")).rows
    except cache.CacheError as error:
        raise RenderError(f"disposable cache unavailable: {error}", error.code) from None
    return (
        [tuple(_text(value) for value in row) for row in hosts],
        [tuple(_text(value) for value in row) for row in vhosts],
    )


def _ip_key(row: tuple[str, ...]) -> tuple[int, ...]:
    try:
        return tuple(int(part) for part in row[0].split("."))
    except (IndexError, ValueError):
        return (999, 999, 999, 999)


def _vlan(ip: str) -> int | None:
    parts = ip.split(".")
    if len(parts) != 4:
        return None
    try:
        return int(parts[2])
    except ValueError:
        return None


def _page_network(
    hosts: list[tuple[str, ...]],
    vlan_names: Mapping[int, str],
    timestamp: str,
) -> str:
    lines = _frontmatter("Network map", timestamp, "network")
    lines.extend(["```mermaid", "graph TD", "  WAN[WAN uplinks] --> OPN[OPNsense router]"])
    for number in sorted({value for row in hosts if (value := _vlan(row[0])) is not None}):
        lines.append(
            f"  OPN --> V{number}[VLAN {number} · {vlan_names.get(number, f'VLAN {number}')}]"
        )
        selected = [row for row in hosts if _vlan(row[0]) == number][:8]
        for row in selected:
            octet = row[0].split(".")[3]
            lines.append(f'  V{number} --> n{number}_{octet}["{row[1]}"]')
    lines.extend(
        [
            "```",
            "",
            "_VLAN names are best-effort; hosts are merged from OPNsense DHCP reservations, firewall",
            "host aliases (the static services), and unique-target DNS records. Up to 8 hosts shown per VLAN._",
        ]
    )
    lines.extend(_footer(timestamp))
    return "\n".join(lines)


def _page_vlans(
    hosts: list[tuple[str, ...]],
    vlan_names: Mapping[int, str],
    timestamp: str,
) -> str:
    lines = _frontmatter("VLANs", timestamp, "network", "vlans")
    if hosts:
        for number in sorted({value for row in hosts if (value := _vlan(row[0])) is not None}):
            lines.extend(
                [
                    f"## VLAN {number} — {vlan_names.get(number, f'VLAN {number}')}  (10.10.{number}.0/24)",
                    "",
                    "| IP | Host / alias | Entity | Source | Notes |",
                    "|----|--------------|--------|--------|-------|",
                ]
            )
            for row in (item for item in hosts if _vlan(item[0]) == number):
                ip, name, source, entity, note = (*row[:5], "", "", "", "", "")[:5]
                shown_entity = f"`{entity}`" if entity else "—"
                lines.append(f"| {ip} | {name} | {shown_entity} | {source} | {note} |")
            lines.append("")
    else:
        lines.append("> [!warning] No firewall/DHCP/guest inventory yet — run the collectors.")
    lines.extend(_footer(timestamp))
    return "\n".join(lines)


def _page_firewall(inventory: Path, firewall: Any | None, timestamp: str) -> str:
    lines = _frontmatter("Firewall", timestamp, "firewall")
    if firewall is None:
        lines.append("> [!warning] No firewall inventory — run `skynet collect opnsense`.")
        lines.extend(_footer(timestamp))
        return "\n".join(lines)
    source = inventory / "firewall/firewall.json"
    document = _object(firewall, source)
    rules = _objects(document.get("rules"), source, "rules")
    aliases = _objects(document.get("aliases"), source, "aliases")
    lines.extend(
        [
            "## Rules",
            "",
            "| Seq | Act | Proto | Source | → Destination : Port | Purpose |",
            "|----:|-----|-------|--------|----------------------|---------|",
        ]
    )
    sequenced = [row for row in rules if row.get("sequence") is not None]
    sequenced.sort(key=lambda row: int(row.get("sequence", 0)))
    for row in sequenced:
        destination = _text(row.get("destination_net"))
        port = _text(row.get("destination_port"))
        if port:
            destination += f":{port}"
        lines.append(
            f"| {_text(row.get('sequence'))} | {_text(row.get('action'))} | "
            f"{_text(row.get('protocol'))} | `{_text(row.get('source_net'))}` | "
            f"`{destination}` | {_text(row.get('description'))} |"
        )
    lines.extend(
        [
            "",
            "## Aliases",
            "",
            "| Alias | Type | Members | Purpose |",
            "|-------|------|---------|---------|",
        ]
    )
    for row in aliases:
        content = _text(row.get("content")).replace("\n", ", ")
        lines.append(
            f"| `{_text(row.get('name'))}` | {_text(row.get('type'))} | {content} | "
            f"{_text(row.get('description'))} |"
        )
    counts = document.get("counts", {})
    count_text = ""
    if isinstance(counts, dict):
        count_text = ", ".join(f"{key}={value}" for key, value in counts.items())
    lines.extend(
        ["", f"_Source: {_text(document.get('source'), 'config mirror')} (L2). {count_text}._"]
    )
    live_path = inventory / "opnsense.json"
    live_value = _json_optional(live_path)
    if live_value is not None:
        live = _object(live_value, live_path)
        firmware = live.get("firmware", {})
        live_counts = live.get("counts", {})
        if not isinstance(firmware, dict) or not isinstance(live_counts, dict):
            raise RenderError(f"{live_path}: malformed live state")
        lines.extend(
            [
                "",
                f"**Live state** (OPNsense API): firmware `{_text(firmware.get('status'))}` · "
                f"{_text(live_counts.get('arp'))} ARP neighbours · "
                f"{_text(live_counts.get('interfaces'))} interfaces · declared-host presence "
                f"{_text(live_counts.get('live'))} live / {_text(live_counts.get('silent'))} "
                f"no-response (ARP+ICMP) — collected {_text(live.get('collected'))}.",
            ]
        )
    lines.extend(_footer(timestamp))
    return "\n".join(lines)


def _node_page(path: Path, value: Any, label: str, timestamp: str) -> tuple[str, str]:
    document = _object(value, path)
    resources = _objects(document.get("resources"), path, "resources")
    pools = _objects(document.get("pools"), path, "pools")
    node = next((_text(row.get("node")) for row in resources if row.get("node")), "")
    node = _filename(node or _text(document.get("node"), label), path)
    lines = _frontmatter(f"Host — {node}", timestamp, "hosts")
    lines.extend(
        [
            f"## Node `{node}`",
            "",
            f"_Snapshot collected: {_text(document.get('collected'), 'unknown')}. "
            "Observations, not service-health verification._",
            "",
        ]
    )
    pool_names = ", ".join(_text(row.get("poolid")) for row in pools if row.get("poolid"))
    if pool_names:
        lines.extend([f"- **Pools:** {pool_names}", ""])
    lines.extend(
        [
            "### Guests",
            "",
            "| VMID | Name | Type | Status | Pool |",
            "|-----:|------|------|--------|------|",
        ]
    )
    guests = [row for row in resources if row.get("type") in {"qemu", "lxc"}]
    guests.sort(key=lambda row: int(row.get("vmid", 0)))
    for row in guests:
        lines.append(
            f"| {_text(row.get('vmid'))} | {_text(row.get('name'))} | {_text(row.get('type'))} | "
            f"{_text(row.get('status'))} | {_text(row.get('pool'))} |"
        )
    lines.extend(
        [
            "",
            "_Excluded from ops pools by policy: OPNsense 5001, CT 635/837, VM 2020 (see AGENTS.md)._",
        ]
    )
    lines.extend(_footer(timestamp))
    return node, "\n".join(lines)


def _page_services(
    inventory: Path,
    vhosts: list[tuple[str, ...]],
    timestamp: str,
) -> str:
    lines = _frontmatter("Services", timestamp, "services")
    dns_path = inventory / "dns-zones.json"
    dns_value = _json_optional(dns_path)
    if dns_value is None:
        lines.append("> [!warning] No DNS inventory — run `skynet collect dns`.")
    else:
        dns = _object(dns_value, dns_path)
        lines.extend(
            [
                "Service records from Technitium zones (A/CNAME):",
                "",
                "| Name | Type | Target |",
                "|------|------|--------|",
            ]
        )
        records: list[tuple[str, str, str]] = []
        for zone in _objects(dns.get("records"), dns_path, "records"):
            for row in _objects(zone.get("records"), dns_path, "records[].records"):
                kind = _text(row.get("type"))
                if kind not in {"A", "CNAME"}:
                    continue
                data = row.get("rData", {})
                if not isinstance(data, dict):
                    raise RenderError(f"{dns_path}: malformed rData")
                records.append(
                    (
                        _text(row.get("name")),
                        kind,
                        _text(data.get("ipAddress") or data.get("cname")),
                    )
                )
        for name, kind, target in sorted(records)[:100]:
            lines.append(f"| {name} | {kind} | `{target}` |")
        lines.extend(
            [
                "",
                "_Per-service pages fill in once `skynet collect docker` populates "
                "`inventory/docker-*.json`._",
            ]
        )
    lines.extend(
        [
            "",
            "## Reverse-proxy vhosts — front door, not a host",
            "",
            "| Vhost | Front door | Proxy |",
            "|-------|-----------|-------|",
        ]
    )
    for vhost_row in vhosts:
        padded = (*vhost_row, "", "", "")
        lines.append(f"| {padded[0]} | `{padded[1]}` ⚠ | {padded[2]} |")
    routes_path = inventory / "routes.json"
    routes_value = _json_optional(routes_path)
    if routes_value is not None:
        routes = _object(routes_value, routes_path)
        lines.extend(
            [
                "",
                "## Route resolution — vanity → front door → backend",
                "",
                "| Vhost | Front door | Backend | Entity | Auth |",
                "|-------|-----------|---------|--------|------|",
            ]
        )
        for row in _objects(routes.get("routes"), routes_path, "routes"):
            lines.append(
                f"| {_text(row.get('vhost'))} | `{_text(row.get('front_door'))}` | "
                f"`{_text(row.get('backend'))}` | `{_text(row.get('backend_entity'))}` | "
                f"{_text(row.get('auth'))} |"
            )
    certs_path = inventory / "certs.json"
    certs_value = _json_optional(certs_path)
    if certs_value is not None:
        certs = _object(certs_value, certs_path)
        rows = _objects(certs.get("certs"), certs_path, "certs")
        rows.sort(
            key=lambda row: (
                float(row["days_left"])
                if isinstance(row.get("days_left"), (int, float))
                else float("inf")
            )
        )
        lines.extend(
            [
                "",
                "## Certificate expiry (soonest first)",
                "",
                "| Endpoint | Days left | Expires | Issuer |",
                "|----------|----------:|---------|--------|",
            ]
        )
        for row in rows:
            if row.get("reachable"):
                days, expires, issuer = (
                    _text(row.get("days_left")),
                    _text(row.get("not_after")),
                    _text(row.get("issuer")),
                )
            else:
                days, expires, issuer = "—", "unreachable", ""
            lines.append(f"| {_text(row.get('label'))} | {days} | {expires} | {issuer} |")
    lines.extend(_footer(timestamp))
    return "\n".join(lines)


def _backup_scope(row: Mapping[str, Any]) -> str:
    if row.get("all") == 1:
        return "all guests"
    if row.get("vmid"):
        return f"VMIDs {row['vmid']}"
    if row.get("pool"):
        return f"pool {row['pool']}"
    return "—"


def _verification_label(value: Any) -> str:
    if value == "ok":
        return "verified"
    if value == "failed":
        return "failed"
    if value == "unknown":
        return "unknown"
    if value is None:
        return "unverified"
    return "unknown"


def _groups(states: Iterable[Any], separator: str) -> str:
    counts: dict[str, int] = {}
    for state in states:
        label = _verification_label(state)
        counts[label] = counts.get(label, 0) + 1
    return ", ".join(f"{key}{separator}{counts[key]}" for key in sorted(counts))


def _page_backup(inventory: Path, timestamp: str) -> str:
    lines = _frontmatter("Backup & grant status", timestamp, "backup")
    lines.extend(
        [
            "## Backup layers (see [[../backup-strategy]])",
            "",
            "| Layer | What | Schedule | Destination |",
            "|-------|------|----------|-------------|",
            "| L3 restic | docker hosts: appdata + protect volumes | nightly 02:30 | "
            "`gdrive:Skynet/Backups/restic/<host>` |",
            "| L5 PBS | PBS datastore mirror | nightly 04:00 | `gdrive:Skynet/Backups/pbs` |",
            "",
            "> [!note] Live snapshot counts need a root grant to read the restic repo; the nightly",
            "> pass records what it can without one. For live counts: `restic snapshots` on the host.",
            "",
            "## Proxmox backup jobs (vzdump)",
            "",
        ]
    )
    job_rows: list[str] = []
    worst = "ok"
    for name in ("proxmox-core.json", "proxmox-network.json"):
        path = inventory / name
        value = _json_optional(path)
        if value is None:
            continue
        document = _object(value, path)
        jobs = _objects(document.get("backup_jobs"), path, "backup_jobs")
        latest = _objects(document.get("backup_last"), path, "backup_last")
        status = _text(latest[0].get("status"), "unknown") if latest else "unknown"
        start = latest[0].get("starttime") if latest else None
        shown_time = "—"
        if isinstance(start, (int, float)):
            shown_time = datetime.fromtimestamp(start, ZoneInfo("Asia/Karachi")).strftime(
                "%Y-%m-%d %H:%M"
            )
        shown_result = (
            "🟢 OK" if status == "OK" else ("⚪ unknown" if status == "unknown" else f"🔴 {status}")
        )
        node = _text(document.get("node"))
        for row in jobs:
            schedule = _text(row.get("schedule"))
            if not schedule:
                continue
            enabled = "yes" if row.get("enabled") == 1 else "**NO**"
            job_rows.append(
                f"| `{node}` | {schedule} | `{_text(row.get('storage'))}` | "
                f"{_backup_scope(row)} | {enabled} | {shown_time} | {shown_result} |"
            )
        if status != "OK":
            worst = "unknown" if status == "unknown" and worst == "ok" else "fail"
        if any(row.get("enabled") != 1 for row in jobs):
            worst = "fail"
    if job_rows:
        notices = {
            "ok": "> [!success] 🟢 Recorded backup jobs enabled; the recorded last vzdump results were OK.",
            "unknown": "> [!note] ⚪ Backup jobs configured, but the last-run result could not be confirmed this pass.",
            "fail": "> [!warning] 🔴 A backup job is disabled or its last run did not return OK — see the table.",
        }
        lines.extend(
            [
                notices[worst],
                "",
                "| Node | Schedule | Storage | Scope | Enabled | Last run (PKT) | Result |",
                "|------|----------|---------|-------|---------|----------------|--------|",
                *job_rows,
            ]
        )
    else:
        lines.append(
            "> [!note] No backup-job data this pass (PVE readonly token idle, or "
            "`/cluster/backup` unreachable)."
        )
    lines.extend(
        [
            "",
            "> [!note] These jobs write to `pbs-unraid` — the PBS datastore below.",
            "",
            "## PBS datastore",
            "",
        ]
    )
    pbs_path = inventory / "pbs.json"
    pbs_value = _json_optional(pbs_path)
    if pbs_value is None:
        lines.append(
            "> [!note] PBS not collected this pass — `inventory/pbs.json` absent "
            "(token idle or PBS unreachable)."
        )
    else:
        pbs = _object(pbs_value, pbs_path)
        stores = _objects(pbs.get("datastores"), pbs_path, "datastores")
        complete = True
        for store in stores:
            store_status = store.get("status")
            groups = store.get("groups")
            numbers = (
                store.get("group_count"),
                store.get("snapshot_total"),
                store.get("unverified"),
            )
            complete = complete and isinstance(store_status, dict) and isinstance(groups, list)
            complete = complete and all(isinstance(item, (int, float)) for item in numbers)
            if isinstance(store_status, dict):
                used, total = store_status.get("used"), store_status.get("total")
                complete = (
                    complete and isinstance(used, (int, float)) and isinstance(total, (int, float))
                )
                if isinstance(used, (int, float)) and isinstance(total, (int, float)):
                    complete = complete and math.isfinite(used) and math.isfinite(total)
                    complete = complete and 0 <= used <= total
        if not complete:
            lines.append(
                "> [!warning] PBS snapshot is incomplete — no backup count or verification state is claimed."
            )
        else:
            snapshots = sum(int(store.get("snapshot_total", 0)) for store in stores)
            groups_count = sum(int(store.get("group_count", 0)) for store in stores)
            unverified = sum(int(store.get("unverified", 0)) for store in stores)
            states = [
                group.get("verify_state")
                for store in stores
                for group in _objects(store.get("groups"), pbs_path, "datastores[].groups")
            ]
            if snapshots == 0:
                lines.append("> [!note] PBS reachable but no snapshots recorded this pass.")
            elif unverified == 0:
                lines.append(
                    f"> [!success] 🟢 All {groups_count} backup groups have a verified latest snapshot "
                    "(state `ok`)."
                )
            else:
                lines.append(
                    f"> [!warning] 🟡 {unverified} latest backup(s) are not verified "
                    f"({_groups(states, '=')}). Schedule a PBS verify job."
                )
            lines.extend(
                [
                    "",
                    "| Datastore | Used / Total | Guests | Snapshots | Unverified | Latest verification |",
                    "|-----------|--------------|-------:|----------:|-----------:|---------------------|",
                ]
            )
            unlisted: list[str] = []
            for store in stores:
                status = store["status"]
                groups = _objects(store.get("groups"), pbs_path, "datastores[].groups")
                used = round(float(status["used"]) / 1099511627776, 1)
                total = round(float(status["total"]) / 1099511627776, 1)
                lines.append(
                    f"| `{_text(store.get('store'))}` | {used:g} / {total:g} TiB | "
                    f"{_text(store.get('group_count'))} | {_text(store.get('snapshot_total'))} | "
                    f"{_text(store.get('unverified'))} | "
                    f"{_groups((row.get('verify_state') for row in groups), ': ')} |"
                )
                for group in groups:
                    if group.get("verify_state") is None:
                        unlisted.append(
                            f"{_text(group.get('ns'))}/{_text(group.get('backup_type'))}/"
                            f"{_text(group.get('backup_id'))}"
                        )
            if unlisted:
                lines.extend(["", f"> [!note] Unverified (latest snapshot): {', '.join(unlisted)}"])
            lines.extend(
                [
                    "",
                    "_`unraid` is NFS-backed on Unraid; L5 mirrors it to `gdrive:Skynet/Backups/pbs` "
                    "(PBS-encrypted + deduped). Targeted Drive→PBS archive recovery is proven; the full "
                    "core-loss rebuild/boot sequence still needs a drill._",
                ]
            )
    lines.extend(["", "## Root-grant audit", ""])
    audit_path = inventory / "grant-audit.json"
    audit_value = _json_optional(audit_path)
    if audit_value is None:
        lines.append(
            "_Pending — harvested from each host's sshd log during a grant "
            "(needs root; nightly skips if none active)._"
        )
    else:
        audit = _objects(audit_value, audit_path, "grant audit")
        lines.extend(["| When | Host | KeyID |", "|------|------|-------|"])
        for row in audit[-30:]:
            lines.append(
                f"| {_text(row.get('when'))} | {_text(row.get('host'))} | `{_text(row.get('keyid'))}` |"
            )
    lines.extend(_footer(timestamp))
    return "\n".join(lines)


def _page_network_gear(inventory: Path, firewall: Any | None, timestamp: str) -> str:
    lines = _frontmatter("Network gear (Omada estate)", timestamp, "netgear")
    path = inventory / "network-gear.json"
    value = _json_optional(path)
    if value is None:
        lines.append(
            "_Pending — `skynet collect omada` has not run (needs the Omada read credential and "
            "reachability; see [[../design/access-and-trust]])._"
        )
        lines.extend(_footer(timestamp))
        return "\n".join(lines)
    document = _object(value, path)
    controller = document.get("controller", {})
    if not isinstance(controller, dict):
        raise RenderError(f"{path}: malformed controller")
    sites = _objects(document.get("sites"), path, "sites")
    devices = _objects(document.get("devices"), path, "devices")
    site_names = ", ".join(_text(site.get("name")) for site in sites)
    lines.extend(
        [
            f"Controller `{_text(controller.get('host'))}` · Omada `{_text(controller.get('version'))}` "
            f"· site(s): {site_names}.",
            "",
            "## Switches & access points",
            "",
            "| Entity | Type | Model | IP | Firmware | Status | Clients | PoE |",
            "|--------|------|-------|----|----------|--------|---------|-----|",
        ]
    )
    for row in devices:
        poe = row.get("poe", {})
        if not isinstance(poe, dict):
            raise RenderError(f"{path}: malformed PoE state")
        shown_poe = f"{_text(poe.get('remain_w'), '?')} W free" if poe.get("support") else "—"
        status = "🟢 up" if row.get("connected") else "🔴 down"
        lines.append(
            f"| `{_text(row.get('entity_id'))}` | {_text(row.get('type'))} | "
            f"{_text(row.get('model'))} | `{_text(row.get('ip'))}` | "
            f"{_text(row.get('firmware'))} | {status} | {_text(row.get('clients'))} | {shown_poe} |"
        )
    for row in devices:
        if row.get("ports") is None:
            continue
        lines.extend(
            [
                "",
                f"### `{_text(row.get('entity_id'))}` — {_text(row.get('name'))} ports",
                "",
                "| Port | Name | Profile | Link | PoE |",
                "|------|------|---------|------|-----|",
            ]
        )
        for port in _objects(row.get("ports"), path, "devices[].ports"):
            lines.append(
                f"| {_text(port.get('port'))} | {_text(port.get('name'), '—')} | "
                f"{_text(port.get('profile'), '—')} | "
                f"{'up' if port.get('link') == 1 else 'down'} | "
                f"{'✓' if port.get('poe', 0) != 0 else '—'} |"
            )
    if firewall is not None:
        fw_doc = _object(firewall, inventory / "firewall/firewall.json")
        fw_ips: set[str] = set()
        for alias in _objects(
            fw_doc.get("aliases"), inventory / "firewall/firewall.json", "aliases"
        ):
            if alias.get("name") not in {"ROLE_INFRASTRUCTURE_SWITCHES", "ROLE_INFRASTRUCTURE_APS"}:
                continue
            fw_ips.update(
                item
                for item in _text(alias.get("content")).splitlines()
                if item.startswith("10.10.")
            )
        seen = {
            _text(row.get("ip")) for row in devices if _text(row.get("ip")).startswith("10.10.")
        }
        lines.extend(
            [
                "",
                "## Firewall reconciliation — reserved vs adopted",
                "",
                "| IP | In firewall INFRASTRUCTURE alias | Adopted in controller |",
                "|----|----------------------------------|-----------------------|",
            ]
        )
        by_ip = {_text(row.get("ip")): _text(row.get("entity_id")) for row in devices}
        for ip in sorted(
            fw_ips | seen, key=lambda value: tuple(int(part) for part in value.split("."))
        ):
            device = f" (`{by_ip[ip]}`)" if ip in by_ip else ""
            lines.append(
                f"| `{ip}` | {'✅' if ip in fw_ips else '—'} | "
                f"{'✅' if ip in seen else '—'}{device} |"
            )
        lines.extend(
            [
                "",
                "> [!note] ✅/— under both columns: a reserved-but-not-adopted IP is a firewall slot with no",
                "> live device; an adopted-but-unreserved IP is gear the `ROLE_INFRASTRUCTURE_*` aliases don't",
                "> cover. Run `bin/ops entities` for the entity-level classification.",
            ]
        )
    lines.extend(_footer(timestamp))
    return "\n".join(lines)


def _index(node_names: list[str], timestamp: str) -> str:
    lines = _frontmatter("Skynet — generated docs", timestamp, "index")
    shown_nodes = "".join(f" [[40-hosts/{name}|{name}]]" for name in node_names) or " _pending_"
    lines.extend(
        [
            "Live view of the lab, rendered from `inventory/` each nightly. **Do not edit** — edit the",
            "collectors or `skynet render docs`.",
            "",
            "- [[05-state-of-the-lab]] — 🖊️ the agent's nightly narrative (human-readable)",
            "- [[06-agent-digest]] — 🤖 recent-activity / episodic / open-thread retrieval view",
            "- [[07-context-map]] — 🧭 on-demand load-cost and context-routing index",
            "- [[00-network-map]] — the map",
            "- [[10-vlans]] — subnets & hosts",
            "- [[20-firewall]] — rules & aliases",
            "- [[30-services/README|Services]]",
            f"- Hosts:{shown_nodes}",
            "- [[50-network-gear]] — switches & APs (Omada estate)",
            "- [[90-backup-status]] — backups & grant audit",
        ]
    )
    lines.extend(_footer(timestamp))
    return "\n".join(lines)


def _remove_tree(path: Path) -> None:
    try:
        shutil.rmtree(path)
    except FileNotFoundError:
        pass
    except OSError:
        pass


def _publish(output: Path, pages: Mapping[Path, str], host_names: set[str]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".skynet-render-", dir=output.parent))
    temporary: Path | None = staging
    backup: Path | None = None
    published = False
    try:
        if output.is_dir():
            shutil.copytree(output, staging, dirs_exist_ok=True)
        for relative, content in pages.items():
            staged = staging / relative
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_text(content, encoding="utf-8")
        hosts = staging / "40-hosts"
        if hosts.is_dir():
            for path in hosts.glob("*.md"):
                if path.name not in host_names:
                    path.unlink()
        if output.exists():
            backup = Path(tempfile.mkdtemp(prefix=".skynet-render-backup-", dir=output.parent))
            backup.rmdir()
            os.replace(output, backup)
        try:
            os.replace(staging, output)
            temporary = None
            published = True
        except OSError:
            if backup is not None:
                try:
                    os.replace(backup, output)
                    backup = None
                except OSError:
                    raise RenderError(
                        f"generated-page publication and rollback failed; prior pages remain at {backup}",
                        3,
                    ) from None
            raise
    except OSError:
        raise RenderError("generated-page publication failed", 3) from None
    finally:
        if temporary is not None:
            _remove_tree(temporary)
        if backup is not None and published:
            _remove_tree(backup)


def render_docs(
    repo: Path, output: Path | None = None, *, timestamp: str | None = None
) -> RenderResult:
    """Build all factual pages, then publish them without exposing failed partial output."""
    repo = repo.resolve()
    inventory = repo / "inventory"
    target = (output or repo / "docs/generated").resolve()
    if not inventory.is_dir():
        raise RenderError("inventory source directory unavailable", 3)
    if not any(path.is_file() and path.stat().st_size for path in inventory.rglob("*.json")):
        raise RenderError("no inventory JSON yet — collectors have not run", 3)
    lab_path = repo / "lab.json"
    lab = _object(_json_optional(lab_path), lab_path)
    vlans = lab.get("vlans", {})
    if not isinstance(vlans, dict):
        raise RenderError(f"{lab_path}: malformed VLAN declarations")
    vlan_names = {
        int(row["vlan"]): _text(row.get("name"))
        for row in _objects(vlans.get("list"), lab_path, "vlans.list")
        if "vlan" in row
    }
    hosts, vhosts = _cache_rows(repo)
    hosts.sort(key=_ip_key)
    moment = timestamp or datetime.now().astimezone().isoformat(timespec="seconds")
    firewall_path = inventory / "firewall/firewall.json"
    firewall = _json_optional(firewall_path)
    pages: dict[Path, str] = {
        Path("00-network-map.md"): _page_network(hosts, vlan_names, moment),
        Path("10-vlans.md"): _page_vlans(hosts, vlan_names, moment),
        Path("20-firewall.md"): _page_firewall(inventory, firewall, moment),
        Path("30-services/README.md"): _page_services(inventory, vhosts, moment),
        Path("90-backup-status.md"): _page_backup(inventory, moment),
        Path("50-network-gear.md"): _page_network_gear(inventory, firewall, moment),
    }
    nodes: list[str] = []
    for label, name in (("core", "proxmox-core.json"), ("network", "proxmox-network.json")):
        path = inventory / name
        value = _json_optional(path)
        if value is None:
            continue
        node, content = _node_page(path, value, label, moment)
        nodes.append(node)
        pages[Path("40-hosts") / f"{node}.md"] = content
    pages[Path("README.md")] = _index(nodes, moment)
    host_names = {path.name for path in pages if path.parent == Path("40-hosts")}
    _publish(target, pages, host_names)
    return RenderResult(target, tuple(sorted(pages)))
