#!/usr/bin/env bash
# render-docs.sh — inventory/*.json + firewall config → docs/generated/ (Obsidian) (docs/design/memory.md)
# USAGE: render-docs.sh
#   Writes Obsidian-flavored markdown (frontmatter, callouts, wikilinks, native Mermaid).
#   docs/generated/ is MACHINE-OWNED — edit THIS renderer, never the output.
#   Every collector that has not run yet degrades gracefully (its section says "pending").
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
inv="${REPO_DIR}/inventory"
gen="${REPO_DIR}/docs/generated"
fw="${inv}/firewall/firewall.json"
ts="$(date -Iseconds)"
mkdir -p "${gen}/30-services" "${gen}/40-hosts"
rm -f "${gen}/40-hosts/"*.md   # node pages are regenerated fresh each run (avoid stale names)

j() { jq -r "$@" 2>/dev/null; }          # quiet jq
has() { [ -s "$1" ]; }                     # file exists + non-empty

# VLAN display names are AUTHORED judgment, so they live in lab.json (SKY-018 P2), not in this
# renderer (ADR 0003). Load the map once; unknown VLANs render as "VLAN N".
lab="${REPO_DIR}/lab.json"
declare -A VLAN_NAME
if has "${lab}"; then
  while IFS=$'\t' read -r num name; do
    [ -n "${num}" ] && VLAN_NAME[${num}]="${name}"
  done < <(j '.vlans.list[]? | "\(.vlan)\t\(.name)"' "${lab}")
fi
vlan_name() { echo "${VLAN_NAME[$1]:-VLAN $1}"; }

fm() { # frontmatter title tag...
  local title="$1"; shift
  printf -- '---\ntitle: %s\ngenerated: %s\ntags: [skynet, generated%s]\n---\n\n' \
    "${title}" "${ts}" "$(printf ', %s' "$@")"
}
foot() { # attribution callout — lives at the BOTTOM of every page
  printf '\n> [!note] Auto-generated by `scripts/render-docs.sh` — do not edit by hand. Last run %s.\n' "${ts}"
}

have_data=0; for f in "${inv}"/*.json "${fw}"; do has "${f}" && have_data=1; done
if [ "${have_data}" -eq 0 ]; then
  echo "no inventory JSON yet — collectors have not run. Nothing to render." >&2; exit 0
fi

# ── host facts — via the rebuildable SQLite join cache (SKY-018 P3) ────────────
# The join that used to be a hand-rolled jq/awk IP-priority ladder here is now SQL keyed on the
# ENTITY id (scripts/sql/host-map.sql over .cache/inventory.db). build-db.sh rebuilds the cache from
# inventory/*.json each run; git stays truth, the DB is throwaway (gitignored). A running guest wins
# its IP and carries its entity id; a DNS name that resolves to a lab.json front door is a vhost, not
# a host (rendered in 30-services). Degrades gracefully if sqlite3 is absent (pre-nixos-rebuild).
# Columns: ip \t name \t source \t entity \t note
hosts_tsv="$(mktemp)"; trap 'rm -f "${hosts_tsv}"' EXIT
SQLITE3="${SQLITE3:-sqlite3}"
db="${REPO_DIR}/.cache/inventory.db"
have_db=0
if ${SQLITE3} --version >/dev/null 2>&1; then
  "${REPO_DIR}/scripts/build-db.sh" >/dev/null 2>&1 || true
  if [ -s "${db}" ]; then
    ${SQLITE3} "${db}" -cmd ".mode tabs" ".read ${REPO_DIR}/scripts/sql/host-map.sql" 2>/dev/null \
      | sort -t. -k3,3n -k4,4n > "${hosts_tsv}" && have_db=1
  fi
fi

# ── 00 — network map (mermaid, from VLANs present in reservations) ─────────────
{
  fm "Network map" network
  echo '```mermaid'
  echo 'graph TD'
  echo '  WAN[WAN uplinks] --> OPN[OPNsense router]'
  # one subgraph per VLAN /24 seen, with its hosts
  awk -F'\t' '{split($1,a,"."); print a[3]}' "${hosts_tsv}" | sort -un | while read -r v; do
    [ -n "${v}" ] || continue
    vn="$(vlan_name "${v}")"
    echo "  OPN --> V${v}[VLAN ${v} · ${vn}]"
    # node id keys on the last octet (unique per host, so same-alias hosts don't collapse).
    awk -F'\t' -v v="${v}" 'BEGIN{n=0} {split($1,a,"."); if(a[3]==v && n<8){printf "  V%s --> n%s_%s[\"%s\"]\n", v, v, a[4], $2; n++}}' "${hosts_tsv}"
  done
  echo '```'
  echo
  echo "_VLAN names are best-effort; hosts are merged from OPNsense DHCP reservations, firewall"
  echo "host aliases (the static services), and unique-target DNS records. Up to 8 hosts shown per VLAN._"
  foot
} > "${gen}/00-network-map.md"

# ── 10 — VLANs (hosts grouped by /24) ─────────────────────────────────────────
{
  fm "VLANs" network vlans
  if [ -s "${hosts_tsv}" ]; then
    awk -F'\t' '{split($1,a,"."); print a[3]}' "${hosts_tsv}" | sort -un | while read -r v; do
      [ -n "${v}" ] || continue
      echo "## VLAN ${v} — $(vlan_name "${v}")  (10.10.${v}.0/24)"
      echo
      echo "| IP | Host / alias | Entity | Source | Notes |"
      echo "|----|--------------|--------|--------|-------|"
      # cols: ip name source entity note — a guest now carries its entity id (SKY-018 P3)
      awk -F'\t' -v v="${v}" '{split($1,a,"."); if(a[3]==v) printf "| %s | %s | %s | %s | %s |\n", $1, $2, ($4==""?"—":"`"$4"`"), $3, $5}' "${hosts_tsv}"
      echo
    done
  elif [ "${have_db}" -eq 0 ]; then
    echo "> [!warning] Host map pending — \`sqlite3\` not available (run \`nixos-rebuild\`) so the join cache could not be built."
  else
    echo "> [!warning] No firewall/DHCP/guest inventory yet — run the collectors."
  fi
  foot
} > "${gen}/10-vlans.md"

# ── 20 — firewall (aliases + rules) ───────────────────────────────────────────
{
  fm "Firewall" firewall
  if has "${fw}"; then
    echo "## Rules"
    echo
    echo "| Seq | Act | Proto | Source | → Destination : Port | Purpose |"
    echo "|----:|-----|-------|--------|----------------------|---------|"
    j '.rules[]? | select(.sequence) | [ .sequence, .action, .protocol, .source_net,
        (.destination_net + (if (.destination_port//"")=="" then "" else ":"+.destination_port end)),
        (.description // "") ] | @tsv' "${fw}" \
      | sort -n \
      | awk -F'\t' '{printf "| %s | %s | %s | `%s` | `%s` | %s |\n", $1,$2,$3,$4,$5,$6}'
    echo
    echo "## Aliases"
    echo
    echo "| Alias | Type | Members | Purpose |"
    echo "|-------|------|---------|---------|"
    j '.aliases[]? | [ .name, .type, ((.content//"")|gsub("\n";", ")), (.description // "") ] | @tsv' "${fw}" \
      | awk -F'\t' '{printf "| `%s` | %s | %s | %s |\n", $1,$2,$3,$4}'
    echo
    src="$(j '.source' "${fw}")"
    echo "_Source: ${src:-config mirror} (L2). $(j '.counts|to_entries|map(.key+"="+(.value|tostring))|join(", ")' "${fw}")._"
    # Live state the config can't give — firmware currency + how many neighbours answered ARP (SKY-020).
    if has "${inv}/opnsense.json"; then
      echo
      echo "**Live state** (OPNsense API): firmware \`$(j '.firmware.status' "${inv}/opnsense.json")\` · $(j '.counts.arp' "${inv}/opnsense.json") ARP neighbours · $(j '.counts.interfaces' "${inv}/opnsense.json") interfaces · declared-host presence $(j '.counts.live' "${inv}/opnsense.json") live / $(j '.counts.silent' "${inv}/opnsense.json") no-response (ARP+ICMP) — collected $(j '.collected' "${inv}/opnsense.json")."
    fi
  else
    echo "> [!warning] No firewall inventory — run \`collect-opnsense.sh\` (live) or \`collect-firewall.sh\` (mirror/DR)."
  fi
  foot
} > "${gen}/20-firewall.md"

# ── 40 — hosts (per Proxmox node: guests + pools) ─────────────────────────────
render_node() { # <label> <json>
  local label="$1" jf="$2"
  has "${jf}" || return 0
  local node; node="$(j 'first(.resources[]? | select(.node) | .node) // .node // empty' "${jf}")"; node="${node:-${label}}"
  {
    fm "Host — ${node}" hosts
    echo "## Node \`${node}\`"
    echo
    local pools; pools="$(j '[.pools[]?.poolid]|join(", ")' "${jf}")"
    [ -n "${pools}" ] && echo "- **Pools:** ${pools}"
    echo
    echo "### Guests"
    echo
    echo "| VMID | Name | Type | Status | Pool |"
    echo "|-----:|------|------|--------|------|"
    j '.resources[]? | select(.type=="qemu" or .type=="lxc")
        | [ .vmid, .name, .type, .status, (.pool // "") ] | @tsv' "${jf}" \
      | sort -n \
      | awk -F'\t' '{printf "| %s | %s | %s | %s | %s |\n", $1,$2,$3,$4,$5}'
    echo
    echo "_Excluded from ops pools by policy: OPNsense 5001, CT 635/837, VM 2020 (see AGENTS.md)._"
    foot
  } > "${gen}/40-hosts/${node}.md"
  echo "${node}"
}
node_list=""
for pair in "core:${inv}/proxmox-core.json" "network:${inv}/proxmox-network.json"; do
  n="$(render_node "${pair%%:*}" "${pair#*:}")"; [ -n "${n}" ] && node_list="${node_list} [[40-hosts/${n}|${n}]]"
done

# ── 30 — services (from DNS records; degrades if DNS not collected) ────────────
{
  fm "Services" services
  local_dns="${inv}/dns-zones.json"
  if has "${local_dns}"; then
    echo "Service records from Technitium zones (A/CNAME):"
    echo
    echo "| Name | Type | Target |"
    echo "|------|------|--------|"
    j '.records[]?.records[]? | select(.type=="A" or .type=="CNAME")
        | [ .name, .type, (.rData.ipAddress // .rData.cname // "") ] | @tsv' "${local_dns}" \
      | sort | awk -F'\t' 'NF>=2{printf "| %s | %s | `%s` |\n", $1,$2,$3}' | head -100
    echo
    echo "_Per-service pages fill in once \`collect-docker.sh\` populates \`inventory/docker-*.json\`._"
  else
    echo "> [!warning] No DNS inventory — run \`collect-dns.sh\`."
  fi
  # Reverse-proxy vhosts: DNS names whose target is a declared front-door alias (lab.json) — a proxy
  # that fans out to many backends, NOT a host (SKY-015 fix, now with a real key behind it — P3).
  if [ "${have_db}" -eq 1 ]; then
    echo
    echo "## Reverse-proxy vhosts — front door, not a host"
    echo
    echo "| Vhost | Front door | Proxy |"
    echo "|-------|-----------|-------|"
    ${SQLITE3} "${db}" -cmd ".mode tabs" ".read ${REPO_DIR}/scripts/sql/vhosts.sql" 2>/dev/null \
      | awk -F'\t' '{printf "| %s | `%s` ⚠ | %s |\n", $1, $2, $3}'
  fi
  # Route resolution chain (SKY-018 P5): vanity name → front door → REAL backend entity → auth mode,
  # from the Caddyfile parse. Answers "where does this actually go" with no manual Caddyfile reading.
  if has "${inv}/routes.json"; then
    echo
    echo "## Route resolution — vanity → front door → backend"
    echo
    echo "| Vhost | Front door | Backend | Entity | Auth |"
    echo "|-------|-----------|---------|--------|------|"
    j '.routes[]? | [ .vhost, .front_door, .backend, .backend_entity, .auth ] | @tsv' "${inv}/routes.json" \
      | awk -F'\t' '{printf "| %s | `%s` | `%s` | `%s` | %s |\n", $1,$2,$3,$4,$5}'
  fi
  # Certificate expiry (SKY-018 P5), soonest first — so an approaching expiry is visible at a glance.
  if has "${inv}/certs.json"; then
    echo
    echo "## Certificate expiry (soonest first)"
    echo
    echo "| Endpoint | Days left | Expires | Issuer |"
    echo "|----------|----------:|---------|--------|"
    j '.certs | sort_by(.days_left) | .[] | if .reachable
        then [ .label, (.days_left|tostring), .not_after, .issuer ] else [ .label, "—", "unreachable", "" ] end | @tsv' "${inv}/certs.json" \
      | awk -F'\t' '{printf "| %s | %s | %s | %s |\n", $1,$2,$3,$4}'
  fi
  foot
} > "${gen}/30-services/README.md"

# ── 90 — backup & grant status ────────────────────────────────────────────────
{
  fm "Backup & grant status" backup
  echo "## Backup layers (see [[../backup-strategy]])"
  echo
  echo "| Layer | What | Schedule | Destination |"
  echo "|-------|------|----------|-------------|"
  echo "| L3 restic | docker hosts: appdata + protect volumes | nightly 02:30 | \`gdrive:Skynet/Backups/restic/<host>\` |"
  echo "| L5 PBS | PBS datastore mirror | nightly 04:00 | \`gdrive:Skynet/Backups/pbs\` |"
  echo
  echo "> [!note] Live snapshot counts need a root grant to read the restic repo; the nightly"
  echo "> pass records what it can without one. For live counts: \`restic snapshots\` on the host."
  echo
  echo "## Root-grant audit"
  echo
  if has "${inv}/grant-audit.json"; then
    echo "| When | Host | KeyID |"
    echo "|------|------|-------|"
    j '.[]? | [.when, .host, .keyid] | @tsv' "${inv}/grant-audit.json" \
      | awk -F'\t' '{printf "| %s | %s | `%s` |\n", $1,$2,$3}' | tail -30
  else
    echo "_Pending — harvested from each host's sshd log during a grant (needs root; nightly skips if none active)._"
  fi
  foot
} > "${gen}/90-backup-status.md"

# ── 50 — network gear (Omada estate, SKY-018 P4) ──────────────────────────────
ng="${inv}/network-gear.json"
{
  fm "Network gear (Omada estate)" netgear
  if has "${ng}"; then
    echo "Controller \`$(j '.controller.host' "${ng}")\` · Omada \`$(j '.controller.version' "${ng}")\` · site(s): $(j '[.sites[].name]|join(", ")' "${ng}")."
    echo
    echo "## Switches & access points"
    echo
    echo "| Entity | Type | Model | IP | Firmware | Status | Clients | PoE |"
    echo "|--------|------|-------|----|----------|--------|---------|-----|"
    j '.devices[]? | [.entity_id, .type, .model, .ip, .firmware,
          (if .connected then "🟢 up" else "🔴 down" end),
          (.clients|tostring),
          (if .poe.support then ((.poe.remain_w//"?"|tostring) + " W free") else "—" end)] | @tsv' "${ng}" \
      | awk -F'\t' '{printf "| `%s` | %s | %s | `%s` | %s | %s | %s | %s |\n", $1,$2,$3,$4,$5,$6,$7,$8}'

    # per-switch port tables
    while IFS=$'\t' read -r sw name; do
      [ -n "${sw}" ] || continue
      echo
      echo "### \`${sw}\` — ${name} ports"
      echo
      echo "| Port | Name | Profile | Link | PoE |"
      echo "|------|------|---------|------|-----|"
      j --arg e "${sw}" '.devices[]? | select(.entity_id==$e) | .ports[]?
            | [.port, (.name//"—"), (.profile//"—"),
               (if .link==1 then "up" else "down" end),
               (if (.poe//0)!=0 then "✓" else "—" end)] | @tsv' "${ng}" \
        | awk -F'\t' '{printf "| %s | %s | %s | %s | %s |\n", $1,$2,$3,$4,$5}'
    done < <(j '.devices[]? | select(.ports!=null) | "\(.entity_id)\t\(.name)"' "${ng}")

    # firewall reconciliation — the estate the firewall RESERVES vs what the controller SEES.
    # This is the drift SKY-018 exists to surface: reserved-but-absent slots, and seen-but-unreserved
    # devices (an AP the INFRASTRUCTURE aliases don't list).
    if has "${fw}"; then
      fw_ips="$(j '.aliases[]? | select(.name=="ROLE_INFRASTRUCTURE_SWITCHES" or .name=="ROLE_INFRASTRUCTURE_APS")
                   | .content | split("\n")[] | select(test("^10\\.10\\."))' "${fw}" | sort -u)"
      seen_ips="$(j '.devices[]?.ip' "${ng}" | sort -u)"
      echo
      echo "## Firewall reconciliation — reserved vs adopted"
      echo
      echo "| IP | In firewall INFRASTRUCTURE alias | Adopted in controller |"
      echo "|----|----------------------------------|-----------------------|"
      printf '%s\n%s\n' "${fw_ips}" "${seen_ips}" | grep -E '^10\.10\.' | sort -u \
        | while IFS= read -r ip; do
            [ -n "${ip}" ] || continue
            in_fw="—"; grep -qxF "${ip}" <<<"${fw_ips}" && in_fw="✅"
            in_ct="—"; grep -qxF "${ip}" <<<"${seen_ips}" && in_ct="✅"
            dev="$(j --arg ip "${ip}" '.devices[]? | select(.ip==$ip) | .entity_id' "${ng}")"
            printf '| `%s` | %s | %s%s |\n' "${ip}" "${in_fw}" "${in_ct}" "${dev:+ (\`${dev}\`)}"
          done
      echo
      echo "> [!note] ✅/— under both columns: a reserved-but-not-adopted IP is a firewall slot with no"
      echo "> live device; an adopted-but-unreserved IP is gear the \`ROLE_INFRASTRUCTURE_*\` aliases don't"
      echo "> cover. Run \`bin/ops entities\` for the entity-level classification."
    fi
  else
    echo "_Pending — \`scripts/collect-network-gear.sh\` has not run (needs the Omada read credential and reachability; see [[../design/access-and-trust]])._"
  fi
  foot
} > "${gen}/50-network-gear.md"

# ── index / MOC ───────────────────────────────────────────────────────────────
{
  fm "Skynet — generated docs" index
  echo "Live view of the lab, rendered from \`inventory/\` each nightly. **Do not edit** — edit the"
  echo "collectors or \`scripts/render-docs.sh\`."
  echo
  echo "- [[05-state-of-the-lab]] — 🖊️ the agent's nightly narrative (human-readable)"
  echo "- [[06-agent-digest]] — 🤖 the agent's cold-boot digest (decisions / open threads / episodes)"
  echo "- [[00-network-map]] — the map"
  echo "- [[10-vlans]] — subnets & hosts"
  echo "- [[20-firewall]] — rules & aliases"
  echo "- [[30-services/README|Services]]"
  echo "- Hosts:${node_list:- _pending_}"
  echo "- [[50-network-gear]] — switches & APs (Omada estate)"
  echo "- [[90-backup-status]] — backups & grant audit"
  foot
} > "${gen}/README.md"

echo "rendered docs/generated/ from inventory (${ts})"
ls "${gen}" "${gen}/40-hosts"
