#!/usr/bin/env bash
# render-docs.sh — inventory/*.json + firewall config → docs/generated/ (Obsidian) (plan §11)
# USAGE: render-docs.sh
#   Writes Obsidian-flavored markdown (frontmatter, callouts, wikilinks, native Mermaid).
#   docs/generated/ is machine-owned — edit THIS renderer, never the output.
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
inv="${REPO_DIR}/inventory"
gen="${REPO_DIR}/docs/generated"
mkdir -p "${gen}/30-services" "${gen}/40-hosts"
ts="$(date -Iseconds)"

have_data=0
for f in "${inv}"/*.json; do [ -e "${f}" ] && have_data=1; done
if [ "${have_data}" -eq 0 ]; then
  echo "no inventory JSON yet — collectors have not run (A3+). Nothing to render." >&2
  exit 0
fi

# 00 — network map (mermaid). Populated from firewall + host inventory when present.
cat > "${gen}/00-network-map.md" <<EOF
---
title: Network map
generated: ${ts}
tags: [skynet, generated, network]
---
> [!note] Auto-generated by \`scripts/render-docs.sh\` — do not edit by hand.

\`\`\`mermaid
graph TD
  WAN[WAN uplinks] --> OPN[OPNsense]
  OPN --> V90[VLAN 90 Ops]
  OPN --> V50[VLAN 50 Infra]
  OPN --> V100[VLAN 100 DMZ]
  V90 --> OPS[vm-skynet-ops 10.10.90.90]
  V100 --> DKR[docker-dmz 10.10.100.15]
\`\`\`
EOF

# 90 — backup + grant status stub, filled from pbs.json/restic state + sshd grant audit.
cat > "${gen}/90-backup-status.md" <<EOF
---
title: Backup & grant status
generated: ${ts}
tags: [skynet, generated, backup]
---
> [!note] Auto-generated — reflects the last collector run.

- restic snapshots: _pending first backup run (A4)_
- PBS snapshots: _pending PBS reachability + collector (A4)_
- Root-grant audit (nightly \`ssh-keygen\` KeyID harvest): _pending first grant (A3)_
EOF

echo "rendered docs/generated/ from inventory (${ts})"
echo "note: richer per-host/per-service/vlan/firewall pages fill in as collectors populate inventory."
