#!/usr/bin/env bash
# render-docs.sh — inventory/*.json + firewall config → docs/generated/ (Obsidian) (plan §11)
# USAGE: render-docs.sh
#   Writes Obsidian-flavored markdown (frontmatter, callouts, wikilinks, native Mermaid).
#   docs/generated/ is MACHINE-OWNED — edit THIS renderer, never the output.
#   Every collector that has not run yet degrades gracefully (its section says "pending").
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
inv="${REPO_DIR}/inventory"
gen="${REPO_DIR}/docs/generated"
fw="${inv}/firewall/firewall.json"
ts="$(date -Iseconds)"
mkdir -p "${gen}/30-services" "${gen}/40-hosts"
rm -f "${gen}/40-hosts/"*.md   # node pages are regenerated fresh each run (avoid stale names)

j() { jq -r "$@" 2>/dev/null; }          # quiet jq
has() { [ -s "$1" ]; }                     # file exists + non-empty

# VLAN name map (best-effort; unknown VLANs render as "VLAN N").
vlan_name() { case "$1" in
  10) echo "Admin";; 20) echo "Storage";; 50) echo "Infrastructure";;
  60) echo "Trusted LAN";; 70) echo "DNS & Services";; 90) echo "Operations";;
  100) echo "DMZ";; *) echo "VLAN $1";; esac; }

fm() { # frontmatter title tag...
  local title="$1"; shift
  printf -- '---\ntitle: %s\ngenerated: %s\ntags: [skynet, generated%s]\n---\n' \
    "${title}" "${ts}" "$(printf ', %s' "$@")"
  printf '> [!note] Auto-generated by `scripts/render-docs.sh` — do not edit by hand. Last run %s.\n\n' "${ts}"
}

have_data=0; for f in "${inv}"/*.json "${fw}"; do has "${f}" && have_data=1; done
if [ "${have_data}" -eq 0 ]; then
  echo "no inventory JSON yet — collectors have not run. Nothing to render." >&2; exit 0
fi

# ── gather host facts (reservations = the DHCP truth: host/ip/mac) ─────────────
# tmp table: "ip\thost\tdescr"
hosts_tsv="$(mktemp)"; trap 'rm -f "${hosts_tsv}"' EXIT
if has "${fw}"; then
  j '.reservations[]? | [.ip, .host, (.descr // "")] | @tsv' "${fw}" | sort -t. -k3,3n -k4,4n > "${hosts_tsv}"
fi

# ── 00 — network map (mermaid, from VLANs present in reservations) ─────────────
{
  fm "Network map" network
  echo '```mermaid'
  echo 'graph TD'
  echo '  WAN[WAN uplinks] --> OPN[OPNsense router]'
  # one subgraph per VLAN /24 seen, with its hosts
  awk -F'\t' '{split($1,a,"."); print a[3]}' "${hosts_tsv}" | sort -un | while read -r v; do
    [ -n "${v}" ] || continue
    vn="$(vlan_name "${v}")"
    echo "  OPN --> V${v}[VLAN ${v} · ${vn}]"
    awk -F'\t' -v v="${v}" 'BEGIN{n=0} {split($1,a,"."); if(a[3]==v && n<8){gsub(/[^a-zA-Z0-9]/,"_",$2); printf "  V%s --> h_%s_%s[%s]\n", v, v, $2, $2; n++}}' "${hosts_tsv}"
  done
  echo '```'
  echo
  echo "_VLAN names are best-effort; subnets/hosts are live from OPNsense DHCP reservations._"
} > "${gen}/00-network-map.md"

# ── 10 — VLANs (hosts grouped by /24) ─────────────────────────────────────────
{
  fm "VLANs" network vlans
  if [ -s "${hosts_tsv}" ]; then
    awk -F'\t' '{split($1,a,"."); print a[3]}' "${hosts_tsv}" | sort -un | while read -r v; do
      [ -n "${v}" ] || continue
      echo "## VLAN ${v} — $(vlan_name "${v}")  (10.10.${v}.0/24)"
      echo
      echo "| IP | Host | Notes |"
      echo "|----|------|-------|"
      awk -F'\t' -v v="${v}" '{split($1,a,"."); if(a[3]==v) printf "| %s | %s | %s |\n", $1, $2, $3}' "${hosts_tsv}"
      echo
    done
  else
    echo "> [!warning] No firewall/DHCP inventory yet — run \`collect-firewall.sh\`."
  fi
} > "${gen}/10-vlans.md"

# ── 20 — firewall (aliases + rules) ───────────────────────────────────────────
{
  fm "Firewall" firewall
  if has "${fw}"; then
    echo "## Rules"
    echo
    echo "| Seq | Act | Proto | Source | → Destination : Port | Purpose |"
    echo "|----:|-----|-------|--------|----------------------|---------|"
    j '.rules[]? | select(.sequence) | [ .sequence, .action, .protocol, .source_net,
        (.destination_net + (if (.destination_port//"")=="" then "" else ":"+.destination_port end)),
        (.description // "") ] | @tsv' "${fw}" \
      | sort -n \
      | awk -F'\t' '{printf "| %s | %s | %s | `%s` | `%s` | %s |\n", $1,$2,$3,$4,$5,$6}'
    echo
    echo "## Aliases"
    echo
    echo "| Alias | Type | Members | Purpose |"
    echo "|-------|------|---------|---------|"
    j '.aliases[]? | [ .name, .type, ((.content//"")|gsub("\n";", ")), (.description // "") ] | @tsv' "${fw}" \
      | awk -F'\t' '{printf "| `%s` | %s | %s | %s |\n", $1,$2,$3,$4}'
    echo
    echo "_Source: \`skynet-opnsense\` config mirror (L2). $(j '.counts|to_entries|map(.key+"="+(.value|tostring))|join(", ")' "${fw}")._"
  else
    echo "> [!warning] No firewall inventory — run \`collect-firewall.sh\`."
  fi
} > "${gen}/20-firewall.md"

# ── 40 — hosts (per Proxmox node: guests + pools) ─────────────────────────────
render_node() { # <label> <json>
  local label="$1" jf="$2"
  has "${jf}" || return 0
  local node; node="$(j 'first(.resources[]? | select(.node) | .node) // .node // empty' "${jf}")"; node="${node:-${label}}"
  {
    fm "Host — ${node}" hosts
    echo "## Node \`${node}\`"
    echo
    local pools; pools="$(j '[.pools[]?.poolid]|join(", ")' "${jf}")"
    [ -n "${pools}" ] && echo "- **Pools:** ${pools}"
    echo
    echo "### Guests"
    echo
    echo "| VMID | Name | Type | Status | Pool |"
    echo "|-----:|------|------|--------|------|"
    j '.resources[]? | select(.type=="qemu" or .type=="lxc")
        | [ .vmid, .name, .type, .status, (.pool // "") ] | @tsv' "${jf}" \
      | sort -n \
      | awk -F'\t' '{printf "| %s | %s | %s | %s | %s |\n", $1,$2,$3,$4,$5}'
    echo
    echo "_Excluded from ops pools by policy: OPNsense 5001, CT 635/837, VM 2020 (see AGENTS.md)._"
  } > "${gen}/40-hosts/${node}.md"
  echo "${node}"
}
node_list=""
for pair in "core:${inv}/proxmox-core.json" "network:${inv}/proxmox-network.json"; do
  n="$(render_node "${pair%%:*}" "${pair#*:}")"; [ -n "${n}" ] && node_list="${node_list} [[40-hosts/${n}|${n}]]"
done

# ── 30 — services (from DNS records; degrades if DNS not collected) ────────────
{
  fm "Services" services
  local_dns="${inv}/dns-zones.json"
  if has "${local_dns}"; then
    echo "Service records from Technitium zones (A/CNAME):"
    echo
    echo "| Name | Type | Target |"
    echo "|------|------|--------|"
    j '.records[]?.records[]? | select(.type=="A" or .type=="CNAME")
        | [ .name, .type, (.rData.ipAddress // .rData.cname // "") ] | @tsv' "${local_dns}" \
      | sort | awk -F'\t' 'NF>=2{printf "| %s | %s | `%s` |\n", $1,$2,$3}' | head -100
    echo
    echo "_Per-service pages fill in once \`collect-docker.sh\` populates \`inventory/docker-*.json\`._"
  else
    echo "> [!warning] No DNS inventory — run \`collect-dns.sh\`."
  fi
} > "${gen}/30-services/README.md"

# ── 90 — backup & grant status ────────────────────────────────────────────────
{
  fm "Backup & grant status" backup
  echo "## Backup layers (see [[../backup-strategy]])"
  echo
  echo "| Layer | What | Schedule | Destination |"
  echo "|-------|------|----------|-------------|"
  echo "| L3 restic | docker hosts: appdata + protect volumes | nightly 02:30 | \`gdrive:Skynet/Backups/restic/<host>\` |"
  echo "| L5 PBS | PBS datastore mirror | nightly 04:00 | \`gdrive:Skynet/Backups/pbs\` |"
  echo
  echo "> [!note] Live snapshot counts need a root grant to read the restic repo; the nightly"
  echo "> pass records what it can without one. For live counts: \`restic snapshots\` on the host."
  echo
  echo "## Root-grant audit"
  echo
  if has "${inv}/grant-audit.json"; then
    echo "| When | Host | KeyID |"
    echo "|------|------|-------|"
    j '.[]? | [.when, .host, .keyid] | @tsv' "${inv}/grant-audit.json" \
      | awk -F'\t' '{printf "| %s | %s | `%s` |\n", $1,$2,$3}' | tail -30
  else
    echo "_Pending — harvested from each host's sshd log during a grant (needs root; nightly skips if none active)._"
  fi
} > "${gen}/90-backup-status.md"

# ── index / MOC ───────────────────────────────────────────────────────────────
{
  fm "Skynet — generated docs" index
  echo "Live view of the lab, rendered from \`inventory/\` each nightly. **Do not edit** — edit the"
  echo "collectors or \`scripts/render-docs.sh\`."
  echo
  echo "- [[05-state-of-the-lab]] — 🖊️ the agent's nightly narrative (human-readable)"
  echo "- [[06-agent-digest]] — 🤖 the agent's cold-boot digest (decisions / open threads / episodes)"
  echo "- [[00-network-map]] — the map"
  echo "- [[10-vlans]] — subnets & hosts"
  echo "- [[20-firewall]] — rules & aliases"
  echo "- [[30-services/README|Services]]"
  echo "- Hosts:${node_list:- _pending_}"
  echo "- [[90-backup-status]] — backups & grant audit"
} > "${gen}/README.md"

echo "rendered docs/generated/ from inventory (${ts})"
ls "${gen}" "${gen}/40-hosts"
